steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  args: ['dotnet', 'publish', '-c', 'Release']
  timeout: 180s
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  args: ['dotnet', 'test', '-v', 'd', '--no-build']
  timeout: 180s
