// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_completed_first_5x5_game = "CgkIxda8tpMKEAIQAg"; // <GPGSID>
        public const string achievement_completed_first_3x3_game = "CgkIxda8tpMKEAIQAQ"; // <GPGSID>
        public const string leaderboard_11x11_best_times = "CgkIxda8tpMKEAIQDA"; // <GPGSID>
        public const string leaderboard_9x9_best_times = "CgkIxda8tpMKEAIQCw"; // <GPGSID>
        public const string achievement_completed_first_game = "CgkIxda8tpMKEAIQAA"; // <GPGSID>
        public const string achievement_completed_first_11x11_game = "CgkIxda8tpMKEAIQBQ"; // <GPGSID>
        public const string achievement_completed_first_9x9_game = "CgkIxda8tpMKEAIQBA"; // <GPGSID>
        public const string achievement_completed_first_7x7_game = "CgkIxda8tpMKEAIQAw"; // <GPGSID>
        public const string event_total_time_played = "CgkIxda8tpMKEAIQEA"; // <GPGSID>
        public const string event_number_of_games_completed = "CgkIxda8tpMKEAIQDw"; // <GPGSID>
        public const string leaderboard_3x3_best_times = "CgkIxda8tpMKEAIQCA"; // <GPGSID>
        public const string achievement_completed_first_13x13_game = "CgkIxda8tpMKEAIQBg"; // <GPGSID>
        public const string leaderboard_13x13_best_times = "CgkIxda8tpMKEAIQDQ"; // <GPGSID>
        public const string leaderboard_15x15_best_times = "CgkIxda8tpMKEAIQDg"; // <GPGSID>
        public const string leaderboard_7x7_best_times = "CgkIxda8tpMKEAIQCg"; // <GPGSID>
        public const string achievement_completed_first_15x15_game = "CgkIxda8tpMKEAIQBw"; // <GPGSID>
        public const string leaderboard_5x5_best_times = "CgkIxda8tpMKEAIQCQ"; // <GPGSID>

}

