name: Check PR Title
on: [pull_request]
jobs:
  check_title:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print Random Message
        run: echo Hello Random Message!
      - name: Print PR Title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo PR Title is $TITLE
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
